<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copyright">
    <div class="copyright-content">
        <span><?= /* @escapeNotVerified */ $block->getCopyright() ?></span>
        <div class="copyright-text">
            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('copyright-text')->toHtml();?>
        </div>
    </div>
</div>
