<?= $block->getBlockContentHtml(); ?>
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "Bargain Buyz",
  "url": "https://www.bargainbuyz.co.uk/",
  "logo": "https://www.bargainbuyz.co.uk/media/logo/stores/1/logo.png",
  "sameAs": [
    "https://www.facebook.com/BargainBuyzLeicester",
    "https://www.instagram.com/Bargain_Buyz"
  ]
}
</script>

<meta property="og:locale" content="en_US" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="Bargain Buyz | Kitchen Appliances | New, Graded & Ex-Display" />
	<meta property="og:description" content="Huge range of Fridge Freezers, Washing Machines, Cookers, Dishwashers &amp; more. Free Leicester delivery. Brands include Samsung, LG, Hotpoint, Neff &amp; many more!" />
	<meta property="og:url" content="https://www.bargainbuyz.co.uk/" />
	<meta property="og:site_name" content="Bargain Buyz" />
	<meta property="article:publisher" content="https://www.facebook.com/BargainBuyzLeicester" />
	<meta property="article:published_time" content="2019-09-02T10:49:09+00:00" />
	<meta property="article:modified_time" content="2020-03-30T11:00:10+00:00" />
	<meta property="og:image" content="https://www.bargainbuyz.co.uk/static/frontend/Ninedotmedia/bargainbuyz/en_GB/Tech9logy_SmartSearch/img/image_2021_11_12T11_16_25_977Z.png" />
	<meta property="og:image:width" content="767" />
	<meta property="og:image:height" content="432" />
	<meta property="fb:app_id" content="198750854413271" />

	<meta name="twitter:card" content="summary" />  
<meta name="twitter:site" content="@BargainBuyz" />  
<meta name="twitter:title" content="Bargain Buyz | Kitchen Appliances | New, Graded & Ex-Display" />  
<meta name="twitter:description" content="Huge range of Fridge Freezers, Washing Machines, Cookers, Dishwashers &amp; more. Free Leicester delivery. Brands include Samsung, LG, Hotpoint, Neff &amp; many more!" />
<meta name="twitter:image" content="https://www.bargainbuyz.co.uk/static/frontend/Ninedotmedia/bargainbuyz/en_GB/Tech9logy_SmartSearch/img/image_2021_11_12T11_16_25_977Z.png" /> 
<meta name="twitter:image:alt" content="Bargain Buyz" /> 