<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<div class="wrap-contact-form">
    <form class="form contact"
          action="<?= $block->escapeUrl($block->getFormAction()) ?>"
          id="contact-form"
          method="post"
          data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
          data-mage-init='{"validation":{}}'>
        <div class="fieldset">
            <strong class="title"><?= $block->escapeHtml(__('Send a message')) ?></strong>
            <div class="holder-wrap-control">
                <div class="wrap-control">
                    <div class="field name required">
                        <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                        <div class="control">
                            <input placeholder="<?= $block->escapeHtmlAttr(__('Enter your name')) ?>" name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                        </div>
                    </div>
                    <div class="field telephone">
                        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Telephone')) ?></span></label>
                        <div class="control">
                            <input placeholder="<?= $block->escapeHtmlAttr(__('Enter your telephone number')) ?>" name="telephone" id="telephone" title="<?= $block->escapeHtmlAttr(__('Telephone')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                        </div>
                    </div>
                </div>
                <div class="wrap-control">
                    <div class="field email required">
                        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                        <div class="control">
                            <input placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>" name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                        </div>
                    </div>
                    <div class="field order-number">
                        <label class="label" for="order_number"><span><?= $block->escapeHtml(__('Order number (optional)')) ?></span></label>
                        <div class="control">
                            <input placeholder="<?= $block->escapeHtmlAttr(__('Enter your order number')) ?>" name="order_number" id="order_number" title="<?= $block->escapeHtmlAttr(__('Order number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('order-number')) ?>" class="input-text" type="text" />
                        </div>
                        <div class="text">
                            <?= $block->escapeHtml(__('Please enter your order number if you have one')) ?>
                        </div>
                    </div>
                </div>
                <div class="wrap-control">
                    <div class="field comment required">
                        <label class="label" for="comment"><span><?= $block->escapeHtml(__('Message')) ?></span></label>
                        <div class="control">
                            <textarea placeholder="<?= $block->escapeHtmlAttr(__('Write your message here.')) ?>" name="comment" id="comment" title="<?= $block->escapeHtmlAttr(__('Write your message here.')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="holder-wrap-control">
                <?= $block->getChildHtml('form.additional.info') ?>
                <div class="actions-toolbar">
                    <div class="primary">
                        <input type="hidden" name="hideit" id="hideit" value="" />
                        <button type="submit" title="<?= $block->escapeHtmlAttr(__('Send')) ?>" class="action submit primary">
                            <span><?= $block->escapeHtml(__('Send')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>

    </form>
</div>
