<?php if (!in_array($this->getRequest()->getModuleName(), ["pointofsale", "checkout"])) : ?>

    <?php
    $helper = $this->helper('Wyomind\PointOfSale\Helper\Data');
    echo $helper->getGoogleMapsApiScript();
    ?>

    <div class="preferred-store-widget">
    <span class="preferred-store-label">
        <?php echo __('Preferred store'); ?>
    </span>
        <span class="preferred-store-selected">

    </span>
        <div class="find-a-store actions-primary">
            <button class="action primary disabled" type="button" title="Find a store">
                <span><?php echo __('Find a store'); ?></span>
            </button>
        </div>
    </div>

    <?php
    $class = $block->getDisplay() == 1 || $block->getDisplay() == 3 ? "_list" : "";
    $class .= $block->getDisplay() == 2 || $block->getDisplay() == 3 ? "_gmap" : "";
    if ($class == "") $class = "_list";
    ?>

    <div id="preferred-store-popup" class="preferred-store-popup preferred-store-loading <?php echo $class; ?>">
    </div>


    <script type="text/x-magento-init">
    {
        ".find-a-store": {
            "Wyomind_PickupAtStore/js/preferred-store":{
                "modalPopup": {
                    "element" : "#preferred-store-popup",
                    "title" : "<?php echo __('Choose your preferred store'); ?>",
                    "contentUrl": "<?php echo $block->getUrl("pickupatstore/section/gmap"); ?>"
                },
                "labels": {
                    "noStoreSelected": "<?php echo __('No store selected'); ?>"
                },
                "autoSelect": <?php echo $block->getAutomatic()?"true":"false"; ?>
            }
        }
    }


    </script>

<?php endif;