<?php $data = $block->getLabelData();
 


 ?>
<?php if ($data && is_array($data)){ ?>
    <div class="<?= (isset($data['class'])) ? $data['class'] : 'promo-label'?>">
        <?php if (isset($data['label'])){ ?>
            
			<?php if($data['class'] == 'promo-guarantee'){ ?>
             
			 <?php if (isset($data['content'])){ ?>
			 <span class="brand_img"><img src="https://staging.bargainbuyz.co.uk/media/attribute/swatch/a/b/warrenty-icon.png"></span> 
            <span><?= $data['content']; ?></span>
        <?php } ?>
			<?php } ?>
			<?php if($data['class'] == 'promo-saved-money'){ ?>	
			
				<div class="save_image_icon">
				<img src="https://staging.bargainbuyz.co.uk/media/attribute/swatch/a/b/save-icon.png" height="30" width="30" style="display: inline;">
				</div>
				<span>
				<span ><?= $data['label']; ?></span>
				 <?php if (isset($data['content'])){ ?>
				<?= $data['content']; ?>
				</span>
				<?php } ?>
			<?php } ?>
        <?php } ?>
        
    </div>
<?php } ?>




