<div class="tabs-wrapper">
    <?php if ($tabs = $block->getCategoryTabs() ):?>
        <div class="tabs">
            <ul class="tab-links">
                <?php foreach ($tabs as $tab): ?>
                    <li class="tab-item" data-config="<?= $tab->getId(); ?>">
                        <a href="#<?= $tab->getUrlKey(); ?>"><?= __($tab->getName()); ?></a>
                    </li>
                <?php endforeach; ?>
            </ul>

            <div class="tab-content"></div>
        </div>
    <?php endif;?>
</div>
<script type="text/x-magento-init">
{
     "*" : {
        "Ninedotmedia_HomeCategoryTabs/js/homepage-tabs" : {
            "url":"<?= $block->getActionUrl(); ?>"
        }
     }
}
</script>
