<style>
			.container{max-width: 1320px; width:100%; margin:0px auto; padding:0px 15px;}
			.holder-content { padding-top: 40px;}
			.holder-content-list-block { float: left; width: 21%; margin-right: 2%;}
			.holder-content .tabs-wrapper { float: right; width: 77%;}
			
			.hp-category-wrap { width: 100%; display: flex; display: -webkit-box; display: -webkit-flex; display: -moz-flex; flex-flow: wrap; flex-flow: wrap;}
			.hp-category-wrap .hp-category-col { width: 31%; margin-bottom: 70px; text-align: center; position: relative;}
			.hp-category-wrap .hp-category-col:nth-child(3n+2) { margin: 0px 3% 70px;}
			.hp-category-wrap .hp-category-col a{text-decoration:none; display: block; overflow: hidden;}
			.hp-category-wrap .hp-category-col a:hover .hp-category-figure img{ -moz-transform: scale(1.1); -webkit-transform: scale(1.1); transform: scale(1.1);}
			.hp-category-wrap .hp-category-col .hp-category-figure{ position:relative; background-color: #fff; padding-bottom: 40px; overflow: hidden; border: solid 1px #ebebeb; border-radius: 10px;}
			.hp-category-wrap .hp-category-col .hp-category-figure:before { content: ''; background-color: #ebebeb; width: 330px; height: 45px; display: none; position: absolute;
				bottom: -20px; left: 0px; z-index: 1; transform: rotate(-5deg); -o-transform: rotate(-5deg); -ms-transform: rotate(-5deg); -moz-transform: rotate(-5deg);}
			.hp-category-wrap .hp-category-col .hp-category-figure img{ width:100%; transition: all 0.5s; -webkit-transition: all 0.5s; -moz-transition: all 0.5s; -ms-transition: all 0.5s; -o-transition: all 0.5s;}
			.hp-category-wrap .hp-category-col .hp-category-text { width: 100%; position: absolute; left: 50%; bottom: -20px; transform: translate(-50%, -0%); -o-transform: translate(-50%, -0%); -ms-transform: translate(-50%, -0%); -moz-transform: translate(-50%, -0%);}
			.hp-category-wrap .hp-category-col .hp-category-text h3 { border-radius: 40px; box-shadow: 2px 2px 15px -6px #ff0000; -webkit-box-shadow: 2px 2px 15px -6px #ff0000;-moz-box-shadow: 2px 2px 15px -6px #003181; border: none; text-decoration: none !important; transition: 0.4s; background-color: #ff0000; max-width: 230px; width: 100%; margin: 0px auto; padding: 12px 10px; color: #fff; font-size: 18px; font-weight: bold;}
			.hp-category-wrap .hp-category-col a:hover .hp-category-text h3{ background-color: #000; box-shadow: 2px 2px 15px -6px #000;  -webkit-box-shadow: 2px 2px 15px -6px #000; -moz-box-shadow: 2px 2px 15px -6px #003181;}
			
			@media only screen and (max-width: 1199px)
			{
				.hp-category-wrap .hp-category-col .hp-category-text h3 {  max-width: 190px; font-size: 16px;}
				
			}
			
		</style>
	<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
        $baseurl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
        ?>

		<div class="container">
			<div class="holder-content">
			
				<div class="tabs-wrapper">
					<div class="hp-category-wrap">
						<div class="hp-category-col">
						<a href="<?php echo $baseurl.'laundry/washing-machines-1.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Washing.jpg'); ?>' alt="image-icon" width="100%" height="100%">
									
								</div>
								<div class="hp-category-text">
									<h3>Washing Machines</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
						<a href="<?php echo $baseurl.'refrigeration.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Fridge.jpg'); ?>' alt="image-icon" width="100%" height="100%">
								
								
								</div>
								<div class="hp-category-text">
									<h3>Fridge Freezers</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
                        <a href="<?php echo $baseurl.'cooking.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Cookers.jpg'); ?>' alt="image-icon" width="100%" height="100%">
								</div>
								<div class="hp-category-text">
									<h3>Cookers</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
                        <a href="<?php echo $baseurl.'refrigeration/american-fridge-freezers.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Freezers.jpg'); ?>' alt="image-icon" width="100%" height="100%">
								</div>
								<div class="hp-category-text">
									<h3>American Fridge Freezers</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
                        <a href="<?php echo $baseurl.'cooking/ovens.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Ovens.jpg'); ?>' alt="image-icon" width="100%" height="100%">
							
									
								</div>
								<div class="hp-category-text">
									<h3>Ovens</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
                        <a href="<?php echo $baseurl.'cooking/hobs.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Hobs.jpg'); ?>' alt="image-icon" width="100%" height="100%">
							
								
								</div>
								<div class="hp-category-text">
									<h3>Hobs</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
                        <a href="<?php echo $baseurl.'laundry/dryers.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Dryer.jpg'); ?>' alt="image-icon" width="100%" height="100%">
							
								
								</div>
								<div class="hp-category-text">
									<h3>Dryer</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
                        <a href="<?php echo $baseurl.'dishwashers.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Dishwashers.jpg'); ?>' alt="image-icon" width="100%" height="100%">
							
									
								</div>
								<div class="hp-category-text">
									<h3>Dishwashers</h3>
								</div>
							</a>
						</div>
						<div class="hp-category-col">
                        <a href="<?php echo $baseurl.'laundry/washer-dryers-1.html'; ?>">
								<div class="hp-category-figure">
                                <img src='<?php echo $this->getViewFileUrl('Ninedotmedia_ProductAttributes::images/Washer-Dryers.jpg'); ?>' alt="image-icon" width="100%" height="100%">
							
									
								</div>
								<div class="hp-category-text">
									<h3>Washer Dryers</h3>
								</div>
							</a>
						</div>
					</div>
				</div>
			</div>
		</div> 	



