<?php
/**
 * Copyright © 2017 ebizmarts. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * @var \Ebizmarts\SagePaySuite\Block\Adminhtml\Order\View\Info $block
 */

$payment = $block->getPayment();

?>

<div class="admin__page-section-item-title" style="margin-top: 20px;">
    <span class="title"><?php echo $block->escapeHtml(__('Opayo Information')); ?></span>

    <div class="actions">
        <a href="<?php echo $block->getSyncFromApiUrl(); ?>">
            <?php echo $block->escapeHtml(__('Sync from API')); ?>
        </a></div>
</div>
<div class="admin__page-section-item-content">
    <div class="order-payment-additional order-payment-method-title">
        <table class="data-table admin__table-secondary">
            <tbody>
            <?php if ($payment->getLastTransId()) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('VPSTxId')); ?>:</th>
                    <td><?php echo $block->escapeHtml($block->getSuiteHelper()->clearTransactionId($payment->getLastTransId())); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("vendorTxCode")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('VendorTxCode')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("vendorTxCode")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("mode")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Mode')); ?>:</th>
                    <td><?php echo strtoupper($block->escapeHtml($payment->getAdditionalInformation("mode"))); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("statusDetail")) {
                $statusDetail = $payment->getAdditionalInformation("statusDetail");
                if (strrpos($payment->getAdditionalInformation("statusDetail"), " : ") !== false) {
                    $statusDetail = explode(" : ", $statusDetail);
                    $statusDetail = $statusDetail[1];
                }
                ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Status')); ?>:</th>
                    <td><?php echo $block->escapeHtml($statusDetail); ?></td>
                </tr>
            <?php } ?>
            <?php $statusCode = $payment->getAdditionalInformation("statusCode"); ?>
            <?php if ($this->isThreeDRedirect($statusCode)) : ?>
                <tr>
                    <td colspan="2">
                        <div align="left" class="message message-info">
                            <p><?php echo $block->getFirstParagraph() ?></p>
                            <p><?php echo $block->getSecondParagraph() ?></p>
                            <p><?php echo $block->getThirdParagraph() ?></p>
                            <p><?php echo $block->getForthParagraph() ?></p>
                        </div>
                    </td>
                </tr>
            <?php endif; ?>
            <?php if ($payment->getAdditionalInformation("3DSecureStatus")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('3D Status')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("3DSecureStatus")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("AddressResult")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Address Verification Result')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("AddressResult")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("PostCodeResult")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Postcode Verification Result')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("PostCodeResult")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("AVSCV2")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('AVS/CV2 Applied')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("AVSCV2")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("CV2Result")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('CV2 Verification Result')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("CV2Result")); ?></td>
                </tr>
            <?php } ?>
            <!-- Compatibility with orders placed with < v.1.2.24 -->
            <?php if ($payment->getAdditionalInformation("threeDStatus")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('3D Status')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("threeDStatus")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckAddress")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Address Verification Result')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckAddress")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckPostalCode")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Postcode Verification Result')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckPostalCode")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckSecurityCode")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('CV2 Verification Result')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckSecurityCode")); ?></td>
                </tr>
            <?php } ?>
            <?php if ($payment->getAdditionalInformation("avsCvcCheckStatus")) { ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('AVS and CV2 Verification Result')); ?>:</th>
                    <td><?php echo $block->escapeHtml($payment->getAdditionalInformation("avsCvcCheckStatus")); ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
</div>

<!--
**************** FRAUD INFORMATION SECTION *******************
-->

<div class="admin__page-section-item-title" style="margin-top: 20px;">
    <span class="title"><?php echo $block->escapeHtml(__('Fraud Information')); ?></span>
</div>
<div class="admin__page-section-item-content">
    <div class="order-payment-additional order-payment-method-title">
        <table class="data-table admin__table-secondary">
            <tbody>
            <?php if (empty($payment->getAdditionalInformation("fraudscreenrecommendation")) ||
                $payment->getAdditionalInformation("fraudscreenrecommendation") == \Ebizmarts\SagePaySuite\Model\Config::T3STATUS_NORESULT ||
                $payment->getAdditionalInformation("fraudscreenrecommendation") == \Ebizmarts\SagePaySuite\Model\Config::REDSTATUS_NOTCHECKED
            ) { ?>
                <tr>
                    <td colspan="2">
                            <?php echo $block->escapeHtml(__('Not enough information.')); ?>
                    </td>
                </tr>
            <?php } else { ?>
                <?php if (!empty($payment->getAdditionalInformation("fraudprovidername"))) { ?>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Provider')); ?>:</th>
                        <td><?php if ($payment->getAdditionalInformation("fraudprovidername") == "ReD") {
                                $html = '<img style="height: 20px;" src="' . $block->getViewFileUrl('Ebizmarts_SagePaySuite::images/red_logo.png') . '">';
                            } else {
                                $html = '<span><img style="height: 20px;vertical-align: text-top;" src="' . $block->getViewFileUrl('Ebizmarts_SagePaySuite::images/t3m_logo.png') . '"> T3M</span>';
                            }
                            echo $html;
                            ?>
                        </td>
                    </tr>
                <?php } ?>
                <tr>
                    <th><?php echo $block->escapeHtml(__('Fraud Recommendation')); ?>:</th>
                    <td><?php $html = $payment->getAdditionalInformation("fraudscreenrecommendation");
                    switch ($html) {
                        case \Ebizmarts\SagePaySuite\Model\Config::REDSTATUS_CHALLENGE:
                        case \Ebizmarts\SagePaySuite\Model\Config::T3STATUS_HOLD:
                            $html = '<span style="color:orange;">' . $html . '</span>';
                            break;
                        case \Ebizmarts\SagePaySuite\Model\Config::REDSTATUS_DENY:
                        case \Ebizmarts\SagePaySuite\Model\Config::T3STATUS_REJECT:
                            $html = '<span style="color:red;">' . $html . '</span>';
                            break;
                    }
                        echo $html;
                    ?>
                    </td>
                </tr>
                <?php if (!empty($payment->getAdditionalInformation("fraudcodedetail"))) { ?>
                    <?php $fraudDetails = $payment->getAdditionalInformation("fraudcodedetail")?>
                <?php } ?>
                <tr title="<?php echo $fraudDetails ?>">
                    <?php $infoImage = '<img style="height: 20px;vertical-align: text-top;" src="' . $block->getViewFileUrl('Ebizmarts_SagePaySuite::images/info.png') . '">' ?>
                    <th><?php echo $block->escapeHtml(__('Fraud Recommendation')); ?>:</th>
                    <td >
                        <?php $html = $payment->getAdditionalInformation("fraudscreenrecommendation");
                        switch ($html) {
                            case \Ebizmarts\SagePaySuite\Model\Config::REDSTATUS_CHALLENGE:
                            case \Ebizmarts\SagePaySuite\Model\Config::T3STATUS_HOLD:
                                $html = '<span style="color:orange;">' . $html . '</span>';
                                break;
                            case \Ebizmarts\SagePaySuite\Model\Config::REDSTATUS_DENY:
                            case \Ebizmarts\SagePaySuite\Model\Config::T3STATUS_REJECT:
                                $html = '<span style="color:red;">' . $html . '</span>';
                                break;
                        }
                        echo $html;
                        ?>
                        <?php echo " " . $infoImage?>
                    </td>
                </tr>
                <?php if (!empty($payment->getAdditionalInformation("fraudcode"))){ ?>
                    <?php $fraudCode = $payment->getAdditionalInformation("fraudcode") ?>
                    <tr title="<?php echo $fraudDetails ?>">
                        <th><?php echo $block->escapeHtml(__('Fraud result')); ?>:</th>
                        <?php if ($fraudCode >= -1000 && $fraudCode <= 29) { ?>
                            <td style="color:#228B22"><?php $html = $payment->getAdditionalInformation("fraudcode");
                                echo $html;
                                ?>
                            </td>
                        <?php } ?>
                        <?php if ($fraudCode >= 30 && $fraudCode <= 49) { ?>
                            <td style="color:#FFA500"><?php $html = $payment->getAdditionalInformation("fraudcode");
                                echo $html;
                                ?>
                            </td>
                        <?php } ?>
                        <?php if ($fraudCode >= 50 && $fraudCode <= 1000) { ?>
                            <td style="color:#FF0000"><?php $html = $payment->getAdditionalInformation("fraudcode");
                                echo $html;
                                ?>
                            </td>
                        <?php } ?>
                    </tr>
                <?php } ?>
                <?php if (!empty($payment->getAdditionalInformation("fraudrules"))) { ?>
                    <tr>
                        <th><a href="" onclick="$('thirdman-breakdown').toggle();return false;"><?php echo $block->escapeHtml(__('Show 3rd Man scores')); ?></a>:</th>
                        <?php $rules = $payment->getAdditionalInformation("fraudrules") ?>
                    </tr>
                <?php } ?>
            <?php } ?>
            </tbody>
        </table>
        <?php if (!empty($payment->getAdditionalInformation("fraudrules"))) { ?>
            <?php $rules = $payment->getAdditionalInformation("fraudrules") ?>
            <table id="thirdman-breakdown" class="data-table admin__table-secondary" style="display:none;">
                <tr>
                    <th style="font-weight: bold"><?php echo $block->escapeHtml(__('DESCRIPTION')); ?>
                        <a href="https://www.opayo.co.uk/file/27231/download-document/Fraud%20Screening%20guide.pdf?token=liPfWBin" target="_blank"><?php echo $block->escapeHtml(__('(More information)')); ?></a>
                    </th>
                    <th style="font-weight: bold"><?php echo $block->escapeHtml(__('SCORE')); ?></th>
                </tr>
                <?php foreach($rules as $rule) { ?>
                    <tr>
                        <td style="text-align:left"><?php echo (string)$rule['description'] ?></td>
                        <td style="text-align:left"><?php echo (string)$rule['score'] ?></td>
                    </tr>
                <?php } ?>
            </table>
        <?php } ?>
    </div>
</div>