<?php $_helper = $this->helper('WeltPixel\QuickCart\Helper\Data'); ?>
<?php if ($_helper->quicartIsEnabled()): ?>
    <script>
        window.openMinicart = '<?php /* @escapeNotVerified */ echo $_helper->openMinicart(); ?>';
        requirejs(['jquery', 'weltpixel_quickcart' ], function($, quickcart) {
            $(document).ready(function() {
                quickcart.initialize();
            });
        });
    </script>
<?php endif; ?>