<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyBrand
 */
?>
<?php
/** @var \Amasty\ShopbyBrand\Block\Widget\BrandList $block */
$items = $block->getIndex();
$columns = abs((int)$block->getData('columns'));
$brandLetters = $block->getAllLetters();
$isShowCount = $block->getData('show_count');
$isShowImages = $block->getData('show_images');
$imgWidth = $block->getImageWidth();
$imgHeight = $block->getImageHeight();
$isShowSearch = $block->getData('show_search');
$isShowFilter = $block->getData('show_filter');
$filterDisplayAll = $block->getData('filter_display_all');
$display_zero = $block->getData('display_zero');
$width = floor(100 / $columns);
?>
<style>
    .brand-images, .bare-list {
        width: 100%;
    }
    .brand-item .am-image-wrapper {
        height: 80px;
    }
    .ambrands-image {
        line-height: 100px;
    }

    .brand-item {
        display: inline-block;
        width: 50%;
        max-width: 50%;
        margin-bottom: 40px;
    }
    .brand-item .no-img {
        line-height: <?= $block->escapeHtml($imgHeight);?>px;
        font-size: 30px;
    }
    @media (min-width: 768px) {
        .brand-item {
            width: 33%;
            max-width: 33%;
        }
    }
</style>
<div class="content">
    <?php if ($items) : ?>
    <div class="brand-images">
        <ul class="bare-list">
        <?php foreach ($items as $letters) : ?>
                <?php foreach ($letters as $letter => $options) : ?>
                                <?php foreach ($options as $o) : ?>
                                    <li class="brand-item" <?= $block->getTooltipAttribute($o);?>>
                                        <a href="<?= $block->escapeUrl($o['url']) ?>"
                                           class="item"
                                           title="<?= $block->escapeHtml($o['label']) ?>">
                                            <?php if ($o['img'] && $isShowImages) : ?>
                                                <div class="am-image-wrapper">
                                                    <img class="ambrands-image"
                                                         src="<?= $block->escapeUrl($o['img']) ?>"
                                                         title="<?= $block->escapeHtml($o['alt']) ?>"
                                                         alt="<?= $block->escapeHtml($o['alt']) ?>" />
                                                </div>
                                            <?php else : ?>
                                                <div class="am-image-wrapper">
                                                    <p class="no-img"><?= $block->escapeHtml($o['label']) ?></p>
                                                </div>
                                            <?php endif ?>
                                            <?php if ($isShowCount) : ?>
                                                <p class="count">(<?= $block->escapeHtml($o['cnt']) ?> items)</p>
                                            <?php endif; ?>
                                        </a>
                                    </li>
                                <?php endforeach ?>
                <?php endforeach ?>
        <?php endforeach ?>
    </ul>
</div>
        <div style="clear:both;"></div>
    <?php else : ?>
        Please select brand attribute in Stores -> Configuration -> Amasty Extensions -> Improved Layered Navigation:
        Brands.
    <?php endif ?>
</div>

<script>
    require([
        'jquery',
        'Amasty_ShopbyBrand/js/brand-filter',
        'domReady!'
    ], function ($) {
        $('[data-ambrands-js="filter-letter"]').on('click', function(e) {
            e.preventDefault();
            $(this).applyBrandFilter('[data-ambrands-js="brand-letter"]');
        });
    });

    <?php if ($block->isTooltipEnabled()) :?>
    require([
        'jquery',
        "mage/tooltip"
    ], function ($) {
        $('[data-amshopby-js="brand-tooltip"]').tooltip({
            position: {
                my: "left-20 bottom",
                at: "right top",
                collision: "flip flip",
                using: function (position, feedback) {
                    $(this).css(position);
                    $("<div>")
                        .addClass("arrow")
                        .addClass(feedback.vertical)
                        .addClass(feedback.horizontal)
                        .appendTo(this);
                }
            },
            tooltipClass: "amshopby-brand-tooltip",
            content: function () {
                var current = $(this).is('li') ? $(this) : $(this).parent();
                return current.data('tooltip-content');
            }
        });
    });
    <?php endif ?>
</script>
